### ISSUE TITLE
 fiftyone.core.service.DatabaseService failed to bind to or

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [PyTorchLightning/lightning-flash#633]
Hi guys,

I hope you are doing great

## 🐛 Bug

If I import `Trainer`

```python
from flash import Trainer
```
I got the following error:

```
{"t":{"$date":"2021-08-05T07:47:51.890Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/zuppif/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/zuppif/.fiftyone/var/lib/mongo/log/mongo.log.2021-08-05T07-47-51"}}
Subprocess ['/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/zuppif/.fiftyone/var/lib/mongo', '--logpath', '/home/zuppif/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Uncaught exception
Traceback (most recent call last):
  File "/home/zuppif/gust-torchvision/playground.py", line 7, in <module>
    from flash import Trainer
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/__init__.py", line 23, in <module>
    from flash.core.data.data_module import DataModule  # noqa: E402
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/data_module.py", line 30, in <module>
    from flash.core.data.data_pipeline import DataPipeline, DefaultPreprocess, Postprocess, Preprocess
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/data_pipeline.py", line 27, in <module>
    from flash.core.data.batch import _DeserializeProcessor, _Postprocessor, _Preprocessor, _Sequential, _SerializeProcessor
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/batch.py", line 22, in <module>
    from flash.core.data.data_source import DefaultDataKeys
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/data_source.py", line 47, in <module>
    from fiftyone.core.collections import SampleCollection
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/__public__.py", line 11, in <module>
    _database_service = fos.DatabaseService()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 203, in __init__
    super().__init__()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 81, in __init__
    self.start()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 293, in start
    food.set_default_port(self.port)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 283, in port
    return self._wait_for_child_port()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 180, in _wait_for_child_port
    return find_port()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 178, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to or
```
### To Reproduce

```python
from flash import Trainer
```

#### Code sample
```python
from flash import Trainer
```

 - PyTorch Version (e.g., 1.0): 1.9.0+cu102
 - OS (e.g., Linux): Ubuntu server 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.10
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:
 - Any other relevant information:

Thanks :)

Francesco

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini thanks for reporting this! Could you try installing from flash master with:
```
pip install 'git+https://github.com/PyTorchLightning/lightning-flash.git#egg=lightning-flash[image]'
```
We've had some changes so that FiftyOne should only be imported now if you actually use it, so that should fix the issue.

Hope that helps :smiley:

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @ethanwharris, thank you for your quick reply. So I've trying to force install it 

```
pip install -I 'git+https://github.com/PyTorchLightning/lightning-flash.git#egg=lightning-flash[image]'

```

But I still get the same error:

```zuppif@blackbird:~/gust-torchvision$ /home/zuppif/gust-torchvision/venv/bin/python3 /home/zuppif/gust-torchvision/playground.py
{"t":{"$date":"2021-08-06T08:09:31.403Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/zuppif/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/zuppif/.fiftyone/var/lib/mongo/log/mongo.log.2021-08-06T08-09-31"}}
Subprocess ['/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/zuppif/.fiftyone/var/lib/mongo', '--logpath', '/home/zuppif/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Uncaught exception
Traceback (most recent call last):
  File "/home/zuppif/gust-torchvision/playground.py", line 3, in <module>
    from flash.image import ImageClassifier
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/__init__.py", line 23, in <module>
    from flash.core.data.data_module import DataModule  # noqa: E402
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/data_module.py", line 30, in <module>
    from flash.core.data.data_pipeline import DataPipeline, DefaultPreprocess, Postprocess, Preprocess
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/data_pipeline.py", line 27, in <module>
    from flash.core.data.batch import _DeserializeProcessor, _Postprocessor, _Preprocessor, _Sequential, _SerializeProcessor
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/batch.py", line 22, in <module>
    from flash.core.data.data_source import DefaultDataKeys
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/data/data_source.py", line 47, in <module>
    from fiftyone.core.collections import SampleCollection
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/__public__.py", line 11, in <module>
    _database_service = fos.DatabaseService()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 203, in __init__
    super().__init__()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 81, in __init__
    self.start()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 293, in start
    food.set_default_port(self.port)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 283, in port
    return self._wait_for_child_port()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 180, in _wait_for_child_port
    return find_port()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fiftyone/core/service.py", line 178, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

Btw what is `fiftyone` used for?

Thanks!

Francesco

**Comment by FrancescoSaverioZuppichini** [comment]
**[UPDATE]** 

Removing `flash` and reinstalling it with 

```
pip install 'git+https://github.com/PyTorchLightning/lightning-flash.git#egg=lightning-flash[image]'
```

Fixed the issue!

Thanks :)

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini glad you got it working. FiftyOne is a visualization tool that can be used directly with flash. Read more here: https://lightning-flash.readthedocs.io/en/latest/integrations/fiftyone.html

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you! Definitely a feature I will be using :)
